# .travis.yml
language: python
python:
    - "3.4"
    - "3.5"

# command to install dependencies
install:
    - "pip install -U pip"

# command to run tests
before_script: cd tests/Introduction
script: py.test
